name: download

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
    paths:
      - '.github/workflows/download.yml'
      - 'JSON/*'
  workflow_dispatch:

jobs:
  download:
    name: Create download
    runs-on: ubuntu-latest
    timeout-minutes: 15 # default is 6 hours!
    steps:

      - name: Git config (global)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global init.defaultBranch main

      # https://github.com/actions/checkout
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Zip packages
        run: |
          # remove (some) subdirectories in root directory
          find . -maxdepth 1 -mindepth 1 -type d -name '.git' -exec rm -rf '{}' ';'
          find . -maxdepth 1 -mindepth 1 -type d -name '.github' -exec rm -rf '{}' ';'
          # remove (some) files in root directory
          find . -maxdepth 1 -mindepth 1 -type f -name '.gitattributes' -delete
          find . -maxdepth 1 -mindepth 1 -type f -name '.gitignore' -delete
          find . -maxdepth 1 -mindepth 1 -type f -name 'README.md' -delete
          find . -maxdepth 1 -mindepth 1 -type f -name 'COMMIT_EDITMSG.txt' -delete
          # remove test files & directories
          find . -depth -type f -path '**/syntax_test_*' -delete -o -type d -path '**/tests' -exec rm -rf '{}' ';'
          # remove empty dirs
          find . -depth -type d -empty -exec rm -rf '{}' ';'
          # zip packages into root
          find . -maxdepth 1 -mindepth 1 -type d -exec sh -c 'cd $1; zip -q -r "$1.sublime-package" "./" -x "tests/*" "**/syntax_test_*"; cd ..; mv "$1/$1.sublime-package" "./";' -- '{}' ';'
          # cleanups folders, now that they were zipped into packages
          find . -depth -maxdepth 1 -mindepth 1 -type d -exec rm -rf '{}' ';'
        shell: bash

      - name: Deploy packages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          allow_empty_commit: false
          build_dir: ./
          commit_message: publish package
          # fqdn: null
          # keep_history: false
          target_branch: download
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
